### PR TITLE
Dmca notice

### PR DESCRIPTION
**Pull request by sparklyballs**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
We've added a notice about it on our news section so all current users should see this.

https://pymedusa.com/news/news.md

**Comment by OmgImAlexis** [comment]
We're looking at getting a zip added to `pymedusa.com` so would you guys be able to switch installs over to using that instead of git until we can fix this?

**Comment by sparklyballs** [comment]
sure that would be possible, keep us informed..

**Comment by OmgImAlexis** [comment]
Here we go. Develop and master zips.

https://pymedusa.com/develop.zip
https://pymedusa.com/master.zip

**Pull request merged**
